"use client";

import React, { createContext, useContext, useState } from "react";

export type Lang = "RU" | "KZ" | "EN";

// ─── Translations ───────────────────────────────────────────────────────────
export const translations = {
  RU: {
    nav: {
      solutions:  "Решения",
      industries: "Отрасли",
      aiAgents:   "AI-Агенты",
      products:   "Продукты & VR",
      cases:      "Кейсы",
      audit:      "Аудит потерь",
      career:     "Карьера",
      about:      "О компании",
      cta:        "Обсудить проект",
    },
    hero: {
      badge1:   "Резидент Astana Hub",
      badge2:   "Казахстан · с 2013 года",
      h1line1:  "Проектируем",
      h1grad:   "цифровую архитектуру",
      h1line2:  "бизнеса",
      sub:      "Создаём корпоративные системы, AI-решения и технологии автоматизации — от анализа процессов до промышленного внедрения.",
      tagline:  "Сначала проектируем. Затем программируем.",
      cta1:     "Обсудить проект",
      cta2:     "Смотреть решения",
      scroll:   "Листайте вниз",
      s1val:    "50+",  s1label: "авторских прав на ПО",
      s2val:    "200+", s2label: "реализованных проектов",
      s3val:    "100+", s3label: "клиентов B2B/B2G",
      s4val:    "13",   s4label: "лет на рынке",
    },
    contact: {
      eyebrow:   "Старт сотрудничества",
      h2a:       "Обсудим цифровую архитектуру",
      h2b:       "вашего бизнеса",
      sub:       "Оставьте заявку. Мы свяжемся с вами в течение 24 часов, проведём предварительную диагностику процессов и предложим решение с дорожной картой внедрения.",
      trust1t:   "Первичный аудит бесплатно",
      trust1d:   "Разбираем ваши текущие системы, выявляем узкие места и точки потери прибыли без предоплаты.",
      trust2t:   "Прямой диалог с Solution-архитектором",
      trust2d:   "С вами общаются инженеры с опытом реальных внедрений, а не менеджеры по продажам.",
      trust3t:   "NDA и защита данных",
      trust3d:   "Подписываем соглашение о неразглашении до передачи любых данных.",
      fName:     "Ваше имя",
      fPhone:    "Телефон / WhatsApp",
      fCompany:  "Компания / должность",
      fType:     "Тип проекта",
      fMsg:      "Кратко опишите задачу",
      fFile:     "Прикрепить ТЗ или файл проекта",
      submit:    "Отправить заявку",
      sent:      "Заявка отправлена!",
      sentSub:   "Архитектор OMIS свяжется с вами в Telegram или WhatsApp в течение 24 часов.",
      sendMore:  "Отправить ещё одну заявку",
    },
    sections: {
      solutionsEyebrow:    "10 технологических направлений",
      solutionsH2a:        "Что мы",
      solutionsH2b:        "автоматизируем",
      chaosEyebrow:        "Проблема большинства предприятий",
      chaosH2a:            "Данные есть.",
      chaosH2b:            "Целостной картины — нет.",
      industriesEyebrow:   "Отраслевая экспертиза",
      industriesH2:        "Отраслевые решения OMIS",
      aiEyebrow:           "Прикладной AI для Enterprise",
      aiH2a:               "Интеллектуальные",
      aiH2b:               "AI-агенты",
      casesEyebrow:        "Подтверждённый опыт",
      casesH2a:            "Реализованные кейсы",
      casesH2b:            "OMIS",
      methodologyEyebrow:  "Инженерная культура OMIS",
      methodologyH2a:      "От диагностики",
      methodologyH2b:      "до внедрения",
      whyEyebrow:          "Надёжный технологический партнёр",
      whyH2a:              "Почему лидеры рынка",
      whyH2b:              "выбирают OMIS",
      founderEyebrow:      "Лидерство и инженерная школа",
      productsEyebrow:     "Собственные продукты и R&D",
      productsH2a:         "Флагманские продукты",
      productsH2b:         "OMIS",
      auditEyebrow:        "Интерактивный экспресс-аудит",
      auditH2a:            "Где ваш бизнес",
      auditH2b:            "теряет эффективность?",
      careerEyebrow:       "Команда и развитие",
      careerH2:            "Карьера в OMIS",
      mapEyebrow:          "Интерактивная карта бизнеса",
      partnersEyebrow:     "Подтверждённые клиенты, институты и технологические партнёры",
    },
  },

  KZ: {
    nav: {
      solutions:  "Шешімдер",
      industries: "Салалар",
      aiAgents:   "AI-Агенттер",
      products:   "Өнімдер & VR",
      cases:      "Кейстер",
      audit:      "Шығын аудиті",
      career:     "Мансап",
      about:      "Компания туралы",
      cta:        "Жобаны талқылау",
    },
    hero: {
      badge1:   "Astana Hub резиденті",
      badge2:   "Қазақстан · 2013 жылдан",
      h1line1:  "Бизнестің",
      h1grad:   "цифрлық архитектурасын",
      h1line2:  "жобалаймыз",
      sub:      "Корпоративтік жүйелер, AI-шешімдер және автоматтандыру технологияларын жасаймыз — процестерді талдаудан өнеркәсіптік енгізуге дейін.",
      tagline:  "Алдымен жобалаймыз. Кейін бағдарламалаймыз.",
      cta1:     "Жобаны талқылау",
      cta2:     "Шешімдерді қарау",
      scroll:   "Төмен айналдырыңыз",
      s1val:    "50+",  s1label: "бағдарламалық авторлық хұқық",
      s2val:    "200+", s2label: "жүзеге асырылған жоба",
      s3val:    "100+", s3label: "B2B/B2G клиенті",
      s4val:    "13",   s4label: "жыл нарықта",
    },
    contact: {
      eyebrow:   "Ынтымақтастықтың басы",
      h2a:       "Бизнесіңіздің цифрлық архитектурасын",
      h2b:       "талқылайық",
      sub:       "Өтінім қалдырыңыз. 24 сағат ішінде хабарласамыз, процестердің алдын ала диагностикасын жүргіземіз.",
      trust1t:   "Алғашқы аудит тегін",
      trust1d:   "Ағымдағы жүйелеріңізді талдаймыз, тар жерлерді анықтаймыз.",
      trust2t:   "Solution-архитекторымен тікелей диалог",
      trust2d:   "Нақты енгізу тәжірибесі бар инженерлер сізбен сөйлеседі.",
      trust3t:   "NDA және деректерді қорғау",
      trust3d:   "Кез келген деректерді берер алдында құпиялылық туралы келісімге қол қоямыз.",
      fName:     "Сіздің атыңыз",
      fPhone:    "Телефон / WhatsApp",
      fCompany:  "Компания / лауазым",
      fType:     "Жоба түрі",
      fMsg:      "Тапсырманы қысқаша сипаттаңыз",
      fFile:     "ТЗ немесе жоба файлын тіркеу",
      submit:    "Өтінім жіберу",
      sent:      "Өтінім жіберілді!",
      sentSub:   "OMIS архитекторы 24 сағат ішінде Telegram немесе WhatsApp арқылы хабарласады.",
      sendMore:  "Тағы өтінім жіберу",
    },
    sections: {
      solutionsEyebrow:    "10 технологиялық бағыт",
      solutionsH2a:        "Не",
      solutionsH2b:        "автоматтандырамыз",
      chaosEyebrow:        "Кәсіпорындардың көпшілігінің мәселесі",
      chaosH2a:            "Деректер бар.",
      chaosH2b:            "Тұтас сурет — жоқ.",
      industriesEyebrow:   "Салалық тәжірибе",
      industriesH2:        "OMIS салалық шешімдері",
      aiEyebrow:           "Enterprise үшін практикалық AI",
      aiH2a:               "Интеллектуалды",
      aiH2b:               "AI-агенттер",
      casesEyebrow:        "Расталған тәжірибе",
      casesH2a:            "OMIS жүзеге асырған",
      casesH2b:            "кейстер",
      methodologyEyebrow:  "OMIS инженерлік мәдениеті",
      methodologyH2a:      "Диагностикадан",
      methodologyH2b:      "енгізуге дейін",
      whyEyebrow:          "Сенімді технологиялық серіктес",
      whyH2a:              "Неге нарық көшбасшылары",
      whyH2b:              "OMIS таңдайды",
      founderEyebrow:      "Көшбасшылық және инженерлік мектеп",
      productsEyebrow:     "Меншікті өнімдер және R&D",
      productsH2a:         "OMIS флагмандық",
      productsH2b:         "өнімдері",
      auditEyebrow:        "Интерактивті экспресс-аудит",
      auditH2a:            "Бизнесіңіз қайда",
      auditH2b:            "тиімділігін жоғалтады?",
      careerEyebrow:       "Команда және даму",
      careerH2:            "OMIS-те мансап",
      mapEyebrow:          "Интерактивті бизнес картасы",
      partnersEyebrow:     "Расталған клиенттер, институттар және технологиялық серіктестер",
    },
  },

  EN: {
    nav: {
      solutions:  "Solutions",
      industries: "Industries",
      aiAgents:   "AI Agents",
      products:   "Products & VR",
      cases:      "Cases",
      audit:      "Loss Audit",
      career:     "Career",
      about:      "About",
      cta:        "Start a Project",
    },
    contact: {
      eyebrow:   "Start Partnership",
      h2a:       "Let's architect the digital",
      h2b:       "backbone of your business",
      sub:       "Leave a request. We'll get back to you within 24 hours, run a preliminary process audit, and propose a solution with a roadmap.",
      trust1t:   "Free Initial Audit",
      trust1d:   "We analyse your current systems, identify bottlenecks and profit leaks — no upfront cost.",
      trust2t:   "Direct Line to a Solution Architect",
      trust2d:   "You talk to engineers with real implementation experience, not sales managers.",
      trust3t:   "NDA & Data Protection",
      trust3d:   "We sign a non-disclosure agreement before you share any data.",
      fName:     "Your name",
      fPhone:    "Phone / WhatsApp",
      fCompany:  "Company / position",
      fType:     "Project type",
      fMsg:      "Briefly describe your task",
      fFile:     "Attach requirements or project brief",
      submit:    "Send Request",
      sent:      "Request Sent!",
      sentSub:   "An OMIS architect will reach you via Telegram or WhatsApp within 24 hours.",
      sendMore:  "Send another request",
    },
    hero: {
      badge1:   "Astana Hub Resident",
      badge2:   "Kazakhstan · since 2013",
      h1line1:  "We architect",
      h1grad:   "the digital backbone",
      h1line2:  "of your business",
      sub:      "We build enterprise systems, AI solutions and automation technologies — from process analysis to full industrial deployment.",
      tagline:  "First we design. Then we code.",
      cta1:     "Start a Project",
      cta2:     "View Solutions",
      scroll:   "Scroll down",
      s1val:    "50+",  s1label: "software copyrights",
      s2val:    "200+", s2label: "completed projects",
      s3val:    "100+", s3label: "B2B/B2G clients",
      s4val:    "13",   s4label: "years in market",
    },
    sections: {
      solutionsEyebrow:    "10 technology directions",
      solutionsH2a:        "What we",
      solutionsH2b:        "automate",
      chaosEyebrow:        "The problem most enterprises face",
      chaosH2a:            "Data exists.",
      chaosH2b:            "A unified picture — does not.",
      industriesEyebrow:   "Industry expertise",
      industriesH2:        "OMIS Industry Solutions",
      aiEyebrow:           "Applied AI for Enterprise",
      aiH2a:               "Intelligent",
      aiH2b:               "AI Agents",
      casesEyebrow:        "Proven track record",
      casesH2a:            "Implemented cases by",
      casesH2b:            "OMIS",
      methodologyEyebrow:  "OMIS Engineering Culture",
      methodologyH2a:      "From diagnosis",
      methodologyH2b:      "to deployment",
      whyEyebrow:          "Your reliable technology partner",
      whyH2a:              "Why market leaders",
      whyH2b:              "choose OMIS",
      founderEyebrow:      "Leadership & Engineering School",
      productsEyebrow:     "Proprietary Products & R&D",
      productsH2a:         "OMIS flagship",
      productsH2b:         "products",
      auditEyebrow:        "Interactive Express Audit",
      auditH2a:            "Where is your business",
      auditH2b:            "losing efficiency?",
      careerEyebrow:       "Team & Growth",
      careerH2:            "Career at OMIS",
      mapEyebrow:          "Interactive Business Map",
      partnersEyebrow:     "Verified clients, institutions and technology partners",
    },
  },
};

// ─── Context ─────────────────────────────────────────────────────────────────
interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  tr: typeof translations.RU;
}

const LanguageContext = createContext<LangCtx>({
  lang: "RU",
  setLang: () => {},
  tr: translations.RU,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("RU");
  const tr = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, tr }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
